/* Action Type Constants for ../reducer/configuration */
export const ADAPTER_ACTION_TYPES = {
    SET_DISCONNECTED: "SET_DISCONNECTED",
    SET_MADNET_CONNECTED: "SET_MADNET_CONNECTED",
    SET_MADNET_ERROR: "SET_MADNET_ERROR",
    SET_MADNET_KEYCHAIN_VALUE: "SET_MADNET_KEYCHAIN_VALUE",
    SET_MADNET_BUSY: "SET_MADNET_BUSY",
    ADD_WALLET_FROM_KEYSTORE: "ADD_WALLET_FROM_KEYSTORE"
}