/* Action Type Constants for ../reducer/transaction Actions */
export const TRANSACTION_ACTION_TYPES = {
    ADD_TO_LIST: "ADD_TO_LIST",
    REMOVE_FROM_LIST: "REMOVE_FROM_LIST",
    UPDATE_FROM_LIST: "UPDATE_FROM_LIST",
    SET_FEE_PAYER: "SET_FEE_PAYER",
    UPDATE_FEES_BY_TYPE: "UPDATE_FEES_BY_TYPE",
    SET_LAST_SENT_TX_HASH: "SET_LAST_SENT_TX_HASH",
    SET_LAST_SENT_MINED_TX: "SET_LAST_SENT_MINED_TX",
    CLEAR_FEE_PAYER: "CLEAR_FEE_PAYER",
}